#   SDK Template, by-EAjks.Com C++ Development Best Practices
#   Copyright (c) 2026 Andrea and Eric DELAGE <Contact@by-EAjks.Com>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: Default CI/CD Pipeline

# Trigger workflow on:
# - Pull requests targeting main branch
# - Pushes to main branch
# - Semantic version tags (e.g., v1.0.0)
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
    tags:
      - 'v\d+.\d+.\d+'

env:
  BUILD_TYPE: Release
  TEMPLATE_SDK_VERSION: '1.2.0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    container:
      image: docker.io/eajkseajks/intel-oneapi-nvidia-cuda:v1-sdk-core
    steps:
      # https://github.com/actions/checkout/tags
      - name: Checkout the Git repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install essential build tools and dependencies
        run: |
          apt update
          apt install --yes \
            wget \
            xz-utils \
            python3.13 \
            python3.13-dev \
            libpython3.13-dev
      - name: Install CMake v4.2.3
        run: |
          wget -c https://github.com/Kitware/CMake/releases/download/v4.2.3/cmake-4.2.3-linux-x86_64.tar.gz -O - | tar -C /opt -xz
          ln -fs /opt/cmake-4.2.3-linux-x86_64/bin/cmake /usr/local/bin/cmake
      - name: Install Infer v1.2.0
        run: |
          wget https://github.com/facebook/infer/releases/download/v1.2.0/infer-linux-x86_64-v1.2.0.tar.xz -O - | tar -C /opt -xJ
          ln -fs /opt/infer-linux-x86_64-v1.2.0/bin/infer /usr/local/bin/infer
      - name: Fetch PR commits explicitly
        run: |
          git fetch \
            origin \
            ${{ github.event.pull_request.base.sha }} \
            ${{ github.event.pull_request.head.sha }}
      - name: Generate changed files index
        run: |
          git diff \
            --name-only \
            ${{github.event.pull_request.base.sha}} \
            ${{github.event.pull_request.head.sha}} \
            > /build-infer.changed-files-index
      - name: Checkout head branch
        run: |
          git checkout ${{github.event.pull_request.head.sha}}
      - name: Analyze code with Infer
        run: |
          . /opt/intel/oneapi/setvars.sh
          cmake \
            -G "Unix Makefiles" \
            -D CMAKE_EXPORT_COMPILE_COMMANDS=1 \
            -D CMAKE_C_COMPILER=clang \
            -D CMAKE_C_COMPILER_AR=llvm-ar \
            -D CMAKE_CXX_COMPILER=clang++ \
            -D CMAKE_CXX_COMPILER_AR=llvm-ar \
            -D CMAKE_UNITY_BUILD=OFF \
            -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -D CMAKE_LINKER_TYPE=DEFAULT \
            -D PYBIND11_FINDPYTHON=ON \
            -D TEMPLATE_SDK_VERSION=${{env.TEMPLATE_SDK_VERSION}} \
            -D USE_PRECOMPILED_HEADERS=OFF \
            -D BUILD_API_DOCUMENTATION=ON \
            -S ./Code \
            -B /build-infer-head
          infer capture \
            --compilation-database /build-infer-head/compile_commands.json \
            --results-dir /build-infer-head.results
          infer analyze \
            --changed-files-index /build-infer.changed-files-index \
            --results-dir /build-infer-head.results \
            --sarif
      - name: Upload security scan results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: /build-infer-base.results/report.sarif
      - name: Checkout base branch
        run: |
          git checkout ${{github.event.pull_request.base.sha}}
      - name: Analyze code with Infer
        run: |
          . /opt/intel/oneapi/setvars.sh
          cmake \
            -G "Unix Makefiles" \
            -D CMAKE_EXPORT_COMPILE_COMMANDS=1 \
            -D CMAKE_C_COMPILER=clang \
            -D CMAKE_C_COMPILER_AR=llvm-ar \
            -D CMAKE_CXX_COMPILER=clang++ \
            -D CMAKE_CXX_COMPILER_AR=llvm-ar \
            -D CMAKE_UNITY_BUILD=OFF \
            -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -D CMAKE_LINKER_TYPE=DEFAULT \
            -D PYBIND11_FINDPYTHON=ON \
            -D TEMPLATE_SDK_VERSION=${{env.TEMPLATE_SDK_VERSION}} \
            -D USE_PRECOMPILED_HEADERS=OFF \
            -D BUILD_API_DOCUMENTATION=ON \
            -S ./Code \
            -B /build-infer-base
          infer capture \
            --reactive \
            --mark-if-unchanged \
            --compilation-database /build-infer-base/compile_commands.json \
            --results-dir /build-infer-base.results
          infer analyze \
            --incremental-analysis \
            --changed-files-index /build-infer.changed-files-index \
            --results-dir /build-infer-base.results \
            --sarif
      - name: Upload security scan results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: /build-infer-base.results/report.sarif
      - name: Compare Infer results and generate report
        run: |
          infer reportdiff \
            --report-current  /build-infer-head.results/report.json \
            --report-previous /build-infer-base.results/report.json \
      - name: Build the project with Intel oneAPI compilers
        run: |
          . /opt/intel/oneapi/setvars.sh
          cmake \
            -G "Unix Makefiles" \
            -D CMAKE_C_COMPILER=icx \
            -D CMAKE_C_COMPILER_AR=llvm-ar \
            -D CMAKE_CXX_COMPILER=icpx \
            -D CMAKE_CXX_COMPILER_AR=llvm-ar \
            -D CMAKE_UNITY_BUILD=OFF \
            -D CMAKE_BUILD_TYPE=Release \
            -D CMAKE_LINKER_TYPE=DEFAULT \
            -D PYBIND11_FINDPYTHON=ON \
            -D TEMPLATE_SDK_VERSION=1.2.0 \
            -D USE_PRECOMPILED_HEADERS=OFF \
            -D BUILD_API_DOCUMENTATION=ON \
            -S ./Code \
            -B /build-package
          make -C /build-package -j$(nproc)
          make -C /build-package package
      # https://github.com/actions/upload-artifact/tags
      - name: Archive the generated Debian package
        uses: actions/upload-artifact@v6
        with:
          name: sdk-package
          path: /build/Template-SDK_*.deb
          retention-days: 7
