#   SDK Template, by-EAjks.Com C++ Development Best Practices
#   Copyright (c) 2026 Andrea and Eric DELAGE <Contact@by-EAjks.Com>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: Default

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
    tags:
      - 'v\d+.\d+.\d+'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/eajkseajks/intel-oneapi-nvidia-cuda:v1-sdk-core
      volumes:
        - ${{github.workspace}}:/src
    steps:
      # https://github.com/actions/checkout/tags
      - name: Checkout the Git repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0
      # https://github.com/reviewdog/action-setup/tags
      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      # Install and run clang-tidy with reviewdog
      - name: Run clang-tidy with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          apt update
          apt install --yes --no-install-recommends clang-tools
          cd /src
          find Code -name "*.cpp" -o -name "*.h" | xargs clang-tidy -p build 2>&1 | reviewdog -f=clang-tidy -reporter=github-pr-review -fail-level=warning
    # # https://github.com/aquasecurity/setup-trivy/tags
    # - name: Set up Trivy manually
    #   uses: aquasecurity/setup-trivy@v0.2.5
    #   with:
    #     version: v0.68.2
    # # https://github.com/aquasecurity/trivy-action/tags
    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     skip-setup-trivy: true
    #     scan-type: repository
    #     severity: CRITICAL,HIGH,MEDIUM
    #     format: sarif
    #     output: trivy-results.sarif
    # # https://github.com/codeql-action/upload-sarif/tags
    # - name: Upload Trivy scan results to GitHub Security
    #   uses: github/codeql-action/upload-sarif@v4
    #   with:
    #     sarif_file: trivy-results.sarif
    #     category: repository-vulnerabilities
    # # https://github.com/aquasecurity/trivy-action/tags
    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     skip-setup-trivy: true
    #     scan-type: fs
    #     severity: CRITICAL,HIGH,MEDIUM
    #     format: sarif
    #     output: trivy-results.sarif
    # # https://github.com/codeql-action/upload-sarif/tags
    # - name: Upload Trivy scan results to GitHub Security
    #   uses: github/codeql-action/upload-sarif@v4
    #   with:
    #     sarif_file: trivy-results.sarif
    #     category: filesystem-vulnerabilities
      - name: Install some required packages
        run: |
          apt update
          apt install --yes --no-install-recommends \
              wget \
              libpython3.14-dev \
              python3.14
          apt-get autoremove --yes --purge
          rm -rf /var/lib/apt/lists/*
      - name: Install a specific CMake version
        run: |
          mkdir /tools && cd /tools
          wget -c https://github.com/Kitware/CMake/releases/download/v4.2.3/cmake-4.2.3-linux-x86_64.tar.gz -O - | tar -xz
      - name: Setup and build the CMake project
        run: |
          mkdir /build && cd /build
          . /opt/intel/oneapi/setvars.sh
          /tools/cmake-4.2.3-linux-x86_64/bin/cmake \
            -G "Ninja" \
            -D CMAKE_C_COMPILER=icx \
            -D CMAKE_C_COMPILER_AR=xiar \
            -D CMAKE_CXX_COMPILER=icpx \
            -D CMAKE_CXX_COMPILER_AR=xiar \
            -D CMAKE_UNITY_BUILD=OFF \
            -D CMAKE_BUILD_TYPE=Release \
            -D CMAKE_LINKER_TYPE=DEFAULT \
            -D PYBIND11_FINDPYTHON=ON \
            -D TEMPLATE_SDK_VERSION=1.2.0 \
            -D USE_PRECOMPILED_HEADERS=OFF \
            -D BUILD_API_DOCUMENTATION=ON \
            /src/Code
          ninja package
      # https://github.com/actions/upload-artifact/tags
      - name: Archive the generated debian package
        uses: actions/upload-artifact@v4.3.4
        with:
          path: /build/Template-SDK_1.2.0.deb
